export * as UserModel from './user.model';
export * as AdminModel from './admin.model';
export * as PatientModel from './patient.model';
export * as DentistModel from './dentist.model';
export * as AppointmentModel from './appointment.model';
export * as MedicalHistoriesModel from './medical-histories.model';
export * as TreatmentHistoriesModel from './treatment-histories.model';
export * as TreatmentModel from './treatment.model';
export * as AttachmentModel from './attachment.model';